name: Test and Deploy

on:
  push:
    branches:
      - main

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo 'hello world from CI'

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and clone repo
        uses: actions/checkout@v2

      - name: Use PostgreSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: test_data
          postgresql user: zaghlol
          postgresql password: breakingbad

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: PGDATABASE=test_data PGUSER=zaghlol PGPASSWORD=breakingbad npm t


